name = "drivers"
title = "MongoDB Drivers"

[constants]
version = 4.0
package-name-org = "docs-ecosystem"
pgp-version = "{+version+}"
toc_landing_pages = ["drivers/docsworker-xlarge/DOP-TESTSLUG/java-drivers", "/java-drivers"]
